### ISSUE TITLE
地址无法访问

### ISSUE THREAD

**Issue by ASCII13** [timqian/resumd#5]
您好：

https://resumd.t9t.io/ 已无法访问，请问是服务挂了，还是决定停止服务了？

**Comment by timqian** [comment]
@ASCII13 我这边是可以访问的，可能是一个网络问题

**Comment by ASCII13** [comment]
我这边一直是这个状态

![20210426144509](https://user-images.githubusercontent.com/8610206/116039999-0b538a80-a69e-11eb-8b25-a2ad5bd5e1ae.jpg)

**Comment by ASCII13** [comment]
附上 522 状态

![20210426144754](https://user-images.githubusercontent.com/8610206/116040294-6b4a3100-a69e-11eb-9958-c139a8753855.jpg)

**Comment by timqian** [comment]
感谢，DNS 配置出了点问题，已修复

**Comment by ASCII13** [comment]
已能正常访问，感谢！
